import '@nutui/nutui-taro/dist/style.css'
import {
  Avatar,
  Icon,
  Button,
  ActionSheet,
  Popup,
  OverLay,
  Divider,
  Progress,
  Popover,
  Tag,
  Navbar,
  Input,
  SearchBar,
  Tabs,
  TabPane,
  Range,
  Price,
  DatePicker,
  Picker,
  Checkbox,
  Grid,
  GridItem,
  Swipe,
  Radio,
  RadioGroup,
  CellGroup,
  Cell,
  Form,
  FormItem,
  Dialog,
  InputNumber,
  Calendar,
  Empty,
  Steps,
  Step,
  AddressList,
  Address,
  Elevator,
} from '@nutui/nutui-taro'
import { App } from 'vue'
const setNutUi = (app: App) => {
  app
    .use(Icon)
    .use(Button)
    .use(Avatar)
    .use(ActionSheet)
    .use(Popup)
    .use(OverLay)
    .use(Divider)
    .use(Progress)
    .use(Popover)
    .use(Tag)
    .use(Navbar)
    .use(Input)
    .use(SearchBar)
    .use(Tabs)
    .use(TabPane)
    .use(Range)
    .use(Price)
    .use(DatePicker)
    .use(Picker)
    .use(Checkbox)
    .use(Grid)
    .use(GridItem)
    .use(Swipe)
    .use(Radio)
    .use(RadioGroup)
    .use(CellGroup)
    .use(Cell)
    .use(Form)
    .use(FormItem)
    .use(Dialog)
    .use(InputNumber)
    .use(Calendar)
    .use(Empty)
    .use(Steps)
    .use(Step)
    .use(AddressList)
    .use(Address)
    .use(Elevator)
}
export default setNutUi
